name: CI
on:
  push:
    branches:
      - master
      - develop

jobs:
  pytest:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: Install bpm-ai-core dependencies
        run: poetry install --directory=bpm-ai-core --with=test
      - name: Install bpm-ai dependencies
        run: poetry install --directory=bpm-ai --with=test
      - name: Run pytest
        run: poetry pytest
