name: Python package
on:
  push:
    tags:
      - "core-v*.*.*"
      - "v*.*.*"

jobs:
  publish-core:
    if: startsWith(github.ref, 'refs/tags/core-v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish core python poetry package
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          # Install project without developer requirements.
          ignore_dev_requirements: "yes"
          package_directory: "bpm-ai-core"

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.11"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          # Install project without developer requirements.
          ignore_dev_requirements: "yes"
          package_directory: "bpm-ai"
